export const READ_APPROVER_REQUESTS_GETTING = '[APPROVE] READ_APPROVER_REQUESTS_GETTING';
export const READ_APPROVER_REQUESTS_COMPLETED = '[APPROVE] READ_APPROVER_REQUESTS_COMPLETED';
export const READ_APPROVER_REQUESTS_ERROR = '[APPROVE] READ_APPROVER_REQUESTS_ERROR';
export const COMPLETE_OPERATION = '[APPROVE] COMPLETE_OPERATION';
export const COMPLETE_OPERATION_ERROR = '[APPROVE] COMPLETE_OPERATION_ERROR';