export const CLOSED_WELLCOME = '[WELLCOME] CLOSED';
export const OPENED_WELLCOME = '[WELLCOME] OPENED';
export const LOADING = '[LOADING] LOADING';
export const READED_BARCODE = '[BARCODE] READED';
export const CHECK_NETWORK = '[CHECK_NETWORK] CHECK_NETWORK';
